### ISSUE TITLE
Feature Request: Enhance Loading Screen Animation for Transaction Fetching

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#105]
**Is your feature request related to a problem? Please describe.**
The current user interface for transaction fetching is not quite good

**Describe the solution you'd like**
Enhance the transaction fetching user interface with a more polished and visually pleasing loading screen animation.

![Screenshot 2023-12-06 at 5 14 04 PM](https://github.com/ani1609/Spendwise/assets/91966855/4706f0b1-9ead-46a0-ba4e-0b61b1f23fcb)

**Comment by tushar-daiya** [comment]
can I work on this?

**Comment by niladrix719** [comment]
@tushar-daiya  sure go ahead
