### ISSUE TITLE
Feature Request: Add Codespaces for Streamlined Development

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#106]
**Is your feature request related to a problem? Please describe.**

Current development setup is not that beginner-friendly

**Describe the solution you'd like**

Integrate Codespaces to offer a standardized, cloud-hosted development environment. This will simplify onboarding for new contributors and ensure a consistent setup for all team members.

Make sure you join our slack channel for better discussions and other announcements.

**Comment by LakshyaSatpal** [comment]
I want to work on this.

**Comment by niladrix719** [comment]
@LakshyaSatpal sure go ahead
