### ISSUE TITLE
Bug : Cannot push code to github

### ISSUE THREAD

**Issue by TamLeCNTT** [ani1609/Spendwise#114]
**Describe the bug**
Since I'm a beginner in open source projects and the github platform, I don't know too much about the issue solving process on github. A few days ago I received a problem for the SpendWise project and I edited it and solved the issue but I don't know how to push the code to github to complete the issue. When I try to push the code, it says :
remote: Permission to ani1609/Spendwise.git denied to TamLeCNTT.
fatal: unable to access 'https://github.com/ani1609/Spendwise.git/': The requested URL returned error: 403.
I hope someone can help me.

![Screenshot 2023-12-08 092511](https://github.com/ani1609/Spendwise/assets/116447152/4f75ab08-f333-45dd-b224-cfe2a4a1815f)

**Comment by ani1609** [comment]
@TamLeCNTT please join the slack channel so that we can guide you over the chat.
