### ISSUE TITLE
BUG FIX: Make the edit transaction and handle transaction buttons visible all the time when the screen width <=480px.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#120]
**Describe the bug**
The buttons are normally visible only when the transactions are hovered. But that should only be the case for large screens where the user will be having a mouse for hovering over the transactions. But for small screens there won't be a mouse for hovering, the buttons should be visible by default.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open https://spendwise-seven.vercel.app in screen size <=480px
2. Add some transactions
3. See the bug

**Expected behaviour**
The buttons should be visible without having to hover over them.

Make sure you join our slack channel for better discussions and other announcements.

**Comment by tushar-daiya** [comment]
Can I work on this?

**Comment by niladrix719** [comment]
@tushar-daiya sure go for it
