### ISSUE TITLE
Feature Request: Implement a Dark Mode for the SpendWise UI with a toggle option

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#121]
Is your feature request related to a problem? Please describe.
Using SpendWise in low-light conditions is straining on the eyes without a Dark Mode, impacting overall user experience.

Describe the solution you'd like
Implement a Dark Mode in the SpendWise UI, providing users with the option to toggle between light and dark interfaces for improved usability, especially in low-light environments.

Make sure you join our slack channel for better discussions and other announcements.

**Comment by Aloksh42** [comment]
Hey @niladrix719 can I work on this issue ?

**Comment by Aloksh42** [comment]
Hey @niladrix719 can I work on this issue ?

**Comment by ani1609** [comment]
@Aloksh42 go ahead with the issue please
