### ISSUE TITLE
Feature Request: Create a PR Template for a more consistent submission process

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#122]
**Is your feature request related to a problem? Please describe.**
The current pull request process could benefit from improvements to provide clearer context and visual representation of changes.

ref : https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository 

**Describe the solution you'd like**

Update the PR template to include:

1. Fixes Reference:
A section to reference the issue or issues being addressed by this pull request (e.g., "Fixes #123").

2. Description of Changes:
A brief overview of the changes made in this PR.

3. Screenshots (If any):
An optional section for contributors to include screenshots or visual representations of the modifications.

Make sure you join our slack channel for better discussions and other announcements.

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by ani1609** [comment]
@IrfanSalim go ahead please.
