### ISSUE TITLE
FEATURE REQUEST: DEVELOP A CATEGORY BASED FILTER FEATURE

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#123]
**Is your feature request related to a problem? Please describe.**
The users cannot filter out the expense transactions for a given category. For example if someone wants to know what are the transactions he/she has made in 'Food' category, he /she has to manually search for the transactions made for food.

**Describe the solution you'd like**
The users should be able to filter out their expense transactions based on category (just like the filter feature available for transaction type wise filter and date wise filter).

Make sure you join our slack channel for better discussions and other announcements.

**Comment by GautamRaj-12** [comment]
I would like to work on this issue..

**Comment by GautamRaj-12** [comment]
I would like to work on this issue.

**Comment by niladrix719** [comment]
@GautamRaj-12 sure go ahead

**Comment by GautamRaj-12** [comment]
I have a question. I have a basic set up of the project done. But how do I access the expense tracker page without logging in/ sign up?
And in firebase, do i need to create my own database and provide it config and do the testing of my feature?

**Comment by niladrix719** [comment]
@GautamRaj-12 no need to config anything everything is pre configured for dev environment, and yes you need to login/signup before accessing the expense tracker page

**Comment by GautamRaj-12** [comment]
Ok..

**Comment by GautamRaj-12** [comment]
hey, I saw the mention issue just now. Do you want me to work on that?
