### ISSUE TITLE
BUG REPORT: The "Add your expenses to see meaningful insights here!" is getting wrapped in two lines.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#130]
**Describe the bug**
When there is no expense transactions hence no expense chart, the  "Add your expenses to see meaningful insights here!" text is getting wrapped in a second line.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://spendwise-seven.vercel.app/
2. Login to your account (or signup) if not already
3. delete all your expense transactions (if any)

**Expected behaviour**
The text should not be wrapped, it should be in the same line.

**Screenshots**
<img width="1189" alt="Screenshot 2023-12-09 at 7 16 16 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/7f9d77e9-55c0-4502-8b9a-d544eed26ba5">

**Comment by gautamjuyal** [comment]
Can I work on this issue as well?

**Comment by ani1609** [comment]
@gautamjuyal this issue has been solved by someone else. please find yourself some other issues.
