### ISSUE TITLE
BUG REPORT: The 'Add Transaction' or 'Edit Transaction lebel getting wrapped up in two lines'

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#131]
**Describe the bug**

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Login to your account (or signup) if not already
3. Reduce the screen size to <374px

**Expected behavior**
The the font size should be shrined to fit the label in a single line

**Screenshots**
<img width="339" alt="Screenshot 2023-12-09 at 7 59 20 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/133198df-4c47-46ab-9038-a6495acdf471">

**Comment by gautamjuyal** [comment]
Can I work on this issue?

**Comment by ani1609** [comment]
@gautamjuyal yes sure
