### ISSUE TITLE
BUG REPORT: The label of the 'Get Started' button is getting wrapped up in a different line.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#132]
Describe the bug

To Reproduce

1. Go to https://spendwise-seven.vercel.app/
2. Logout of your account (if previously logged in)
3. Reduce the screen size to <408px

Expected behavior
The the font size should be shrined to fit the label in a single line

Screenshots
<img width="403" alt="Screenshot 2023-12-09 at 8 07 42 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/76f78d1c-835d-456a-8714-43d036d14558">

**Comment by SahilNalavade** [comment]
hey hii

**Comment by niladrix719** [comment]
@SahilNalavade hello

**Comment by SahilNalavade** [comment]
I'll clone and look into it

**Comment by niladrix719** [comment]
sure go ahead i am assigning you this

**Comment by SahilNalavade** [comment]
cool

**Comment by SahilNalavade** [comment]
Should I create a fork?

**Comment by niladrix719** [comment]
yes, you can follow the get started docs: https://github.com/ani1609/Spendwise#getting-started

**Comment by ani1609** [comment]
@SahilNalavade yeah you need to fork the repository and clone it to your local machine and then push all the codes into the forked repository.

**Comment by SahilNalavade** [comment]
Okay cool

**Comment by SahilNalavade** [comment]
I've create a pull request, you may review the latest commit.
