### ISSUE TITLE
CODE OPTIMISATION: Refactor Code for Improved Modularity - Transactions Component

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#133]
<img width="433" alt="Screenshot 2023-12-09 at 9 41 00 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/2d70838b-d1ca-4061-86fc-6f5ec82983da">

**Description:**
The current code in ExpenseTracker.js has become intricate, and to enhance modularity, it's proposed to create a new component, Transactions.js, responsible for rendering the list of transactions. This refactor aims to make the codebase more organised and maintainable.

**Steps:**

1. Create a new component, Transactions.js, within the components folder.
2. Pass the transactions state variable from ExpenseTracker.js to Transactions.js as props.
3. Inside Transactions.js, handle the rendering of transactions in the same style as the current implementation along with the filter functionality.
4. Transfer the edit and delete functionalities from ExpenseTracker.js to Transactions.js for a more focused component responsibility.

Note- The above mentioned steps are just an overview of the concept. Join our slack channel (if not joined) and get your confusions cleared (if any).

**Expected Benefits:**

-> Improved code modularity with a dedicated component for rendering transactions.
-> Clearer separation of concerns, making the codebase easier to understand and maintain (keeping the same functionalities as of now).
-> Enhanced reusability of the Transactions component in other parts of the application.

**Comment by chandiran-v** [comment]
Can I work on this?

**Comment by ani1609** [comment]
@chandiran-v yes please!

**Comment by chandiran-v** [comment]
Hey I have tried but not able to work with this, because it is way advanced. Please unassign me. It's miscommunication. I'll make sure it'll never happen again. @ani1609

**Comment by niladrix719** [comment]
@chandiran-v no worries

**Comment by LakshyaSatpal** [comment]
I can take this.

**Comment by Nupoor10** [comment]
Hello, can I work on this?

**Comment by niladrix719** [comment]
@Nupoor10 sure

**Comment by ani1609** [comment]
@Nupoor10 any update?

**Comment by Nupoor10** [comment]
Hello, I am working on it will have the PR up by tomorrow
