### ISSUE TITLE
CODE OPTIMISATION: Enhance Code Organisation - TransactionForm Component

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#134]
*Description:*
To streamline the code structure and improve maintainability, it is recommended to create a new component, TransactionForm.js, dedicated to handling the addition of transactions to the database. This refactoring effort aims to establish a clear separation of concerns, with a focused component for transaction form-related functionalities.

*Steps:*

1. Introduce a new component, TransactionForm.js, within the components folder.
2. Move the transaction form-related code, including input fields and form logic, from ExpenseTracker.js to TransactionForm.js.
3. Implement the necessary functionality for adding transactions to the database within TransactionForm.js.
3. Pass any required state variables or functions from ExpenseTracker.js to TransactionForm.js as props.

*Expected Benefits:*

Improved code modularity with a dedicated component for handling transaction forms.
Enhanced readability and maintainability of the ExpenseTracker component.
A clear separation of concerns, making it easier to understand and manage code related to transaction form interactions.
![Screenshot 2023-12-09 at 9 04 21 PM](https://github.com/ani1609/Spendwise/assets/91966855/7cfb3b8a-89d4-4ffe-adb3-2b05aa668ea4)

**Comment by LakshyaSatpal** [comment]
I can work on this.

**Comment by niladrix719** [comment]
@LakshyaSatpal sure go ahead
