### ISSUE TITLE
FEATURE REQUEST: Set left and right paddings of the Navbar to 30px.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#137]
Set left and right paddings of the Navbar to 30px for screen sizes <=768px.

<img width="769" alt="Screenshot 2023-12-10 at 2 43 02 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/eec4210b-e3a6-4ffa-ad19-c4da60e15de7">

**Comment by SahilNalavade** [comment]
I'll like to give it a go

**Comment by ani1609** [comment]
@SahilNalavade sure! Go ahead.

**Comment by SahilNalavade** [comment]
Hi, Can you help me create 2 pull requests

**Comment by ani1609** [comment]
@SahilNalavade sure. please come over our slack channel for a bette communication.
