### ISSUE TITLE
BUG REPORT: Login-signup buttons overlapping for small screens.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#138]
**Describe the bug**
The login and signup buttons seem to be overlapping each other for screen sizes <=480px.

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/ on a divice having screen size <=480px (or use browser inspect feature to lower the content screen)
2. Log out from your account (if logged in previously).

**Expected behavior**
The buttons should fit in the navbar properly

**Screenshots**
<img width="481" alt="Screenshot 2023-12-10 at 2 54 55 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/70b8437f-a8be-427f-af68-b3897ff83bd5">

**Comment by SahilNalavade** [comment]
![Before](https://github.com/ani1609/Spendwise/assets/84601587/12af58f5-e045-47b9-8999-ca16509974da)
![After](https://github.com/ani1609/Spendwise/assets/84601587/0e55a6ca-2cb7-4347-b5cd-e47725722be1)

**Comment by SahilNalavade** [comment]
This should be fixed by latest updates

**Comment by chandiran-v** [comment]
Hey, can I work on this?

**Comment by ani1609** [comment]
@SahilNalavade as you have made your comment before anyone else, i am assigning you the issue. Please make required changes for this particular issue and create a relevant PR so that there won't be a mess for us to guide the contributors.

**Comment by ani1609** [comment]
@chandiran-v please look for some other issues.
