### ISSUE TITLE
Bug: Disabled Category field should show Disabled Cursor

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#141]
**Describe the bug**
When Category Field is Disabled it shows pointer cursor

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app
2. Select Transaction Type 'Income'
3. Hover on Select Category
4. The cursor shows pointer which should not be the case

**Expected behavior**
A Disabled Cursor should be shown like this: 

**Screenshots**
![97821087-f7d2e400-1c65-11eb-93d2-44e8260c1850](https://github.com/ani1609/Spendwise/assets/91966855/ca35f8ad-bfef-4d6a-ada5-1660b14c53f6)

**Comment by Jaimin25** [comment]
I would like to work on this

**Comment by ani1609** [comment]
@Jaimin25 yes sure
