### ISSUE TITLE
BUG REPORT: The chart labels are getting wrapped in a two different lines

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#148]
**Describe the bug**
The chart labels 'Food', 'Travel', 'Shopping', 'Bills', and 'Others' are getting wrapped in a two different lines

**To Reproduce**
Steps to reproduce the behavioir:
1. Go to https://spendwise-seven.vercel.app/ in screen size <=408px (you can use browser's inspect property for that)
2. Login to your account (or create one)
3. Add expense transaction(s)
4. Scroll to the bottom of the page
5. See the error

**Expected behaviour**
All the labels should be in the same line

**Screenshots**
<img width="395" alt="Screenshot 2023-12-10 at 4 29 15 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/ffe0cdeb-1495-4994-8723-74e953f4e81a">

**Comment by chandiran-v** [comment]
Hey, can I work on this?

**Comment by ani1609** [comment]
@chandiran-v sure

**Comment by chandiran-v** [comment]
Hi, is this issue still persist? I think I fixed this and merged right?

**Comment by ani1609** [comment]
@ani1609 yes the issue is solved. Forgot to close the issue, my bad...
