### ISSUE TITLE
Bug: Very Long Description Breaks the UI

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#149]
**Describe the bug**
Very Long Description of transaction Breaks the ui

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app
2. Add a Transaction with a very long description
3. See error

**Expected behavior**
We can show starting words and hide the rest to have a better UI

**Screenshots**
![Screenshot 2023-12-10 at 4 35 16 PM](https://github.com/ani1609/Spendwise/assets/91966855/79c7e172-7be8-4d44-afe3-922aa97be355)

**Comment by Jaimin25** [comment]
Would like to work on this

**Comment by niladrix719** [comment]
sure
