### ISSUE TITLE
FEATURE REQUEST: Add styles to the filter forms

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#151]
<img width="360" alt="Screenshot 2023-12-10 at 4 59 17 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/b095a0ef-3910-4c55-b86d-8e67f0dfad3c">

Refer to the ExpenseTracker.js file and add styles to the filter section according to the above Ui.

**Comment by GautamRaj-12** [comment]
I will be happy to contribute to this.

**Comment by niladrix719** [comment]
@GautamRaj-12 assigned

**Comment by GautamRaj-12** [comment]
The project is using both tailwind css as well as external css. So how do i style it. Using tailwind or changing styles in ExpenseTracker.css

**Comment by niladrix719** [comment]
@GautamRaj-12 you can use any option, both will be fine

**Comment by ani1609** [comment]
@GautamRaj-12 use any (but personally tailwind css is recommended)

**Comment by GautamRaj-12** [comment]
ok Got it

**Comment by GautamRaj-12** [comment]
Have a look. 
On small viewports, it is overflowing out of the container. So should i decrease the width? But dd-mm-yyyy will takes its own width. Or should I allow it to wrap on small viewports?


https://github.com/ani1609/Spendwise/assets/64408989/7df83463-a6e9-478d-86f3-59a372540e01

**Comment by ani1609** [comment]
@GautamRaj-12 try giving relative widths to the forms
