### ISSUE TITLE
Bug: Ui of New Button seems uneven from colour prospective

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#154]
**Describe the bug**
Ui of New Button seems uneven from colour prospective

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app
2. Create a Transaction
3. Hover over the created transaction and click on edit icon
4. The 'New' button will show up on the form

**Expected behavior**
UI and colour should be constant

**Screenshots**

![Screenshot 2023-12-10 at 6 34 29 PM](https://github.com/ani1609/Spendwise/assets/91966855/9d9839ad-5d4e-4e2a-afd4-47701c1017a5)

**Comment by chandiran-v** [comment]
Can I work and fix along with #148 issue?

**Comment by niladrix719** [comment]
@chandiran-v i guess separate PR for separate issue should be there

**Comment by chandiran-v** [comment]
Then can you assign this issue to me?
