### ISSUE TITLE
Docs: Add Tech stack icons instead of just names in README

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#156]
**Is your feature request related to a problem? Please describe.**
Currently we have only text based info in README

https://github.com/ani1609/Spendwise#built-with

**Describe the solution you'd like**
Lets Add Tech stack icons instead of just names

![Screenshot 2023-12-10 at 6 56 36 PM](https://github.com/ani1609/Spendwise/assets/91966855/fb378c6a-a127-4b93-a1d9-84756438fa0d)

**Comment by DevHrithik** [comment]
Hello @niladrix719, I would like to take care of this problem. Could you please assign it to me? My plan is to include icons of the technology stacks involved, and make them clickable. Once clicked, they will lead you to the official documentation or homepage of that particular tech stack.

**Comment by ani1609** [comment]
@DevHrithik go ahead with the issue please.
