### ISSUE TITLE
UI: The signup/login Button should have same width as the input fields

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#157]
**Is your feature request related to a problem? Please describe.**
The signup/login button does not seems align with input fields ui

**Describe the solution you'd like**
The signup/login Button should have same width as the input fields

![Screenshot 2023-12-10 at 7 07 36 PM](https://github.com/ani1609/Spendwise/assets/91966855/0c0cb014-6e25-430e-9214-6a57cdeabd15)
![Screenshot 2023-12-10 at 7 07 43 PM](https://github.com/ani1609/Spendwise/assets/91966855/87d4c9c2-9bbe-4eab-9812-6521ee3e6b04)

**Comment by iimamul** [comment]
can i work on this ?

**Comment by ani1609** [comment]
@iimamul go ahead with the issue please

**Comment by iimamul** [comment]
@ani1609 signup/login width of the input box and UI seams different too. I fixed that too.  Should I PR this with this issue ? or have to create new issue for input and UI width ?

**Comment by ani1609** [comment]
@iimamul please push the relevant codes in relevant issues. push the styling of the buttons here and i am assigning you the issue regarding different widths. push the code there.

**Comment by ani1609** [comment]
@iimamul are you there in our slack channel? If not, please join and text me, there seems to be a conflict because another guy has pushed his code into the same issue as yours.

**Comment by iimamul** [comment]
ok @ani1609 joining
