### ISSUE TITLE
UI and Input width different in Login/SignUp page

### ISSUE THREAD

**Issue by iimamul** [ani1609/Spendwise#164]
**Describe the bug**
login/signup page UI and input box width are different.

**Expected behavior**
login/signup page UI and input box width should be the same.

**Screenshots**
![image](https://github.com/ani1609/Spendwise/assets/17052424/2f945f6c-4db3-4d70-9589-64ff7d130768)
![image](https://github.com/ani1609/Spendwise/assets/17052424/95db3bc2-1773-413e-ab83-998557ced667)

can I go with this one?

**Comment by ani1609** [comment]
@iimamul sure
