### ISSUE TITLE
IMAGE TYPE CONVERSION: Convert the default banner image to .webp format.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#170]
**Steps for image conversion**

1. Go t client/src/images folder
2. Find the image named as default.png
3. convert the image to .webp format

**Steps for changing the image path for using the new .webp image**

1. Go to client/src/components/NoUserjs
2. Change the image path import Default from "../images/default.png"; at line 3 for importing the new .webp image

**Comment by DevHrithik** [comment]
I would love to work on this issue as well could you please assign this issue to me?

**Comment by AnupK1234** [comment]
Hey @ani1609 !
I would like to work on this issue.
Could you please assign it to me ?
Thank you

**Comment by ani1609** [comment]
@DevHrithik sure.

**Comment by ani1609** [comment]
@AnupK1234 please keep an eye on the next upcoming issues.
