### ISSUE TITLE
FILTER UI TWEAK: Change the Ui of the Transaction type drop down menu of filter.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#174]
Go to the client/src/components/ExpenseTracker.js and find a select from at line 489.

<img width="143" alt="Screenshot 2023-12-11 at 4 10 29 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/9d1386c0-2331-4a85-a739-7fd1e232b4f9">
(ignore the heading "Component 1" in the image

Change the ui of the form to the above mentioned Ui.

**Comment by anand-harsh** [comment]
Hi @ani1609 Can you please assign me this issue

**Comment by ani1609** [comment]
@anand-harsh sure!

**Comment by anand-harsh** [comment]
Hi @ani1609 

![image](https://github.com/ani1609/Spendwise/assets/94885893/ef217652-8cfc-4dda-ac0b-103a68d174de)


I have made the changes like this, is it ok?
If you approve I will push the codes
