### ISSUE TITLE
FILTER UI TWEAK: Change the Ui of the category drop down menu of filter.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#175]
Go to the client/src/components/ExpenseTracker.js and find a select from at line 497.

<img width="157" alt="Screenshot 2023-12-11 at 4 10 22 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/e4a286f8-1ed4-454d-817a-449814527762">

(ignore the heading "Component 2" in the image

Change the ui of the form to the above mentioned Ui. There will be a 'All' above all options in the list (as in the ExpenseTracker.js file)

**Comment by anand-harsh** [comment]
Hi @ani1609 Can you please assign me this issue

**Comment by ani1609** [comment]
@anand-harsh yes sure

**Comment by niladrix719** [comment]
@anand-harsh any updates?

**Comment by anand-harsh** [comment]
> @anand-harsh any updates?

I have raised the PR for Similar functionality at #203 , So, if this PR got approved then I will finish this issue by that day.
Is it okay?

**Comment by niladrix719** [comment]
sure take you time

**Comment by anand-harsh** [comment]
@ani1609 Sir, why this issue is unassigned to me?, I have been working on this since 3 days and trying to improve with your requirement and without and feedback , You unassigned the issue.

**Comment by ani1609** [comment]
@anand-harsh I have been requesting you to review the changes based on the given ui references. But none of the time your code meets the required changes or outcomes.


https://github.com/ani1609/Spendwise/assets/89239354/f3458995-8752-49d0-8cc1-6eaf06a1eff8

**Comment by anand-harsh** [comment]
> @anand-harsh I have been requesting you to review the changes based on the given ui references. But none of the time your code meets the required changes or outcomes.
> 
> Uploading Screen Recording 2023-12-17 at 5.05.50 PM.mov…

Kindly check the recent push

**Comment by anand-harsh** [comment]
> @anand-harsh I have been requesting you to review the changes based on the given ui references. But none of the time your code meets the required changes or outcomes.
> 
>  Screen.Recording.2023-12-17.at.5.05.50.PM.mov

https://github.com/ani1609/Spendwise/pull/203#issuecomment-1859135630

Isn't this the same you needed?

**Comment by ani1609** [comment]
@anand-harsh i would like you to se the design you have developed. It does not seem to be the design shown in the above video.

**Comment by ani1609** [comment]
@anand-harsh in your code, when the menu is opened, the transactions are pushed down. That is not the design shown in the video

**Comment by anand-harsh** [comment]
> @anand-harsh in your code, when the menu is opened, the transactions are pushed down. That is not the design shown in the video

okay so you should have told me, then I would have fixed it. Now other people will use my codes to fix the issue + This wasted my time as you closed both PR without and mid-feedbacks. I have contributed to Freecodecamp, ACM, so I dont think without proper midvalution and feedback, closing a PR is a good practise. Its just my review on this.

**Comment by ani1609** [comment]
@anand-harsh please don't instruct the mentors on how the project should be maintained. The issue was assigned to you last week, you created three pull request with two review changes. Still you are not meeting the required criteria of the designs required. We cannot hold on to such developers, KWoC has a specific time limit, we don't have the whole year for resolving a beginner level issue.

**Comment by anand-harsh** [comment]
> @anand-harsh please don't instruct the mentors on how the project should be maintained. The issue was assigned to you last week, you created three pull request with two review changes. Still you are not meeting the required criteria of the designs required. We cannot hold on to such developers, KWoC has a specific time limit, we don't have the whole year for resolving a beginner level issue. And apart from this, the plagiarism that you stated is not gonna happen because your code was not merged with the main branch.

Sir, I am not instructing you, as the option of the select cant be customised using css like padding and margin. So I had made a custom dropdown. So in the latest push, just color and border issue is there which can be fixed in a minute. And sorry if I was rude to you, It wasn't my intention.

**Comment by ani1609** [comment]
@anand-harsh get on the slack channel and txt me

**Comment by ani1609** [comment]
@anand-harsh please get this done by today
