### ISSUE TITLE
Add styles to Category and Date select inuputs under Add New Transaction Section

### ISSUE THREAD

**Issue by GautamRaj-12** [ani1609/Spendwise#177]
The  "Choose a Category" and "date" selection inputs under Add new Transaction section should be given the styles consistent to other select inputs.
![image](https://github.com/ani1609/Spendwise/assets/64408989/611cfd66-9667-4794-9991-86e5b013dd9c)

And Even if the above design is part of the UI, there is a minor issue related to how different browsers style selection input.
The same input box is styled  with a greyish background color on Mozilla Firefox which does not look good.
No background color in Chrome
![image](https://github.com/ani1609/Spendwise/assets/64408989/3fb312b4-4a07-415b-8aee-33be048bdb1d)
But 
Greyish background color in Firefox
![image](https://github.com/ani1609/Spendwise/assets/64408989/d07314b3-91a8-4902-af0e-558eb28e14fe)

Solution:

- Go to ExpenseTracker.js.
- Find the required select inputs.
- Change the styles.
- Make Background as transparent so that the select inputs are displayed same on every browser.

**Comment by chandiran-v** [comment]
Hey, can I work on this?

**Comment by ani1609** [comment]
@chandiran-v yeah sure
