### ISSUE TITLE
BUG REPORT: Transaction type select form and category select form in filter not showing pointer as cursor

### ISSUE THREAD

**Issue by gitcommitankit** [ani1609/Spendwise#184]
**Describe the bug**
The cursor is not changing to 'pointer' type when hovering over type filter and category filter in transactions filter

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Log into your account (or create if not already)
3. Add transactions
4. Hover over type filter and category filter
5. see the error

**Expected behaviour**
The cursor should change to 'pointer' type

<img width="278" alt="Screenshot 2023-12-12 at 2 35 18 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/2708ecda-29d2-4395-8167-6d13c6da4977">

**Comment by Jaimin25** [comment]
I would like to work on this one

**Comment by ani1609** [comment]
@Jaimin25 sure
