### ISSUE TITLE
BUG REPORT: The filter feature should not be shown when there is no transactions at all.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#185]
**Describe the bug**
The filter feature is being showed up been when there is no transaction

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Log into your account (or create if not already)
3. Remove all transactions (if any)

**Expected behavior**
The filter utility should not be rendered whent here is no transactions at all.

**Screenshots**
<img width="466" alt="Screenshot 2023-12-12 at 2 47 05 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/60972716-b6ef-4367-a4cf-0ec649f93463">

**Comment by chandiran-v** [comment]
Can I work on this?

**Comment by ani1609** [comment]
@chandiran-v sure
