### ISSUE TITLE
FEATURE REQUEST: Develop a dedicated profile section for the users.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#187]
**Description:**
We would like to request the implementation of the frontend for the Profile.js component in our GitHub project. The goal is to enhance the user profile section of our application. We have a design mockup available on Figma that provides detailed specifications and styling guidelines.

**Figma Link:** https://www.figma.com/file/LRX1qh4axVMFBn9qVbpSEK/Expense-Tracker?type=design&node-id=0-1&mode=design&t=7UOKsCKZCfLZ9Gtz-0 (Screen: desktop 4)

Develop only the frontend part of the sidebar as of now.

<img width="140" alt="Screenshot 2023-12-12 at 3 23 27 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/7e7e3e16-baf3-4b06-b797-01d13c3d844a">

**Tasks:**
Implement the Profile.js component based on the Figma design.
Ensure responsiveness and compatibility with various devices and screen sizes.
Follow the established coding conventions and guidelines of the project.

**Comment by harshikagoyal14** [comment]
@ani1609 I can work on this issue, can you please assign it to me

**Comment by ani1609** [comment]
@harshikagoyal14 sure

**Comment by harshikagoyal14** [comment]
Sir I have completed the sidebar and its in the sky blue colour as shown in figma , and also i added the functionality that whenever the mouse will go to left part of the dashboard the sidebar will open. Is there anything more to do?

**Comment by ani1609** [comment]
@harshikagoyal14 upload a screenshot please

**Comment by harshikagoyal14** [comment]
![Image 12-12-23 at 11 36 PM](https://github.com/ani1609/Spendwise/assets/109340203/5f816c03-79d1-4931-8cbb-009a8bea1818)
![Image 12-12-23 at 11 36 PM](https://github.com/ani1609/Spendwise/assets/109340203/c11b4ade-0569-4687-8b10-2842e9631cb9)
Have a look

**Comment by ani1609** [comment]
@harshikagoyal14 looks good. create a PR

**Comment by harshikagoyal14** [comment]
@ani1609 I have made a PR. Can you pls check

**Comment by ani1609** [comment]
@harshikagoyal14 It seems there was a mistake from our side, the issue does not contain enough instructions. Are you one our slack channel? If not, then please join and ping me up, i will explain you the issue.

**Comment by harshikagoyal14** [comment]
@ani1609 Ok
