### ISSUE TITLE
BUG REPORT: Both the signup button and continue with google are having same amount of animation delay.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#189]
**Describe the bug**
Both the signup button and 'continue with google' button are having same amount of animation delay.

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Log out of your account if previously signed in
3. Click on the signup button on the navbar
4. See that both the are showing up at the same time.

file directory- client/src/components/Signup.js

https://github.com/ani1609/Spendwise/assets/89239354/3d2b95e0-1630-4075-ac4b-f7e0e66c0a8d

**Expected behaviour**
The 'continue with google' button should show up after 200ms of the signup button.
Set the animation-delay of signup button to 1300ms and that of the 'continue with google' will be 1500ms

**Comment by SharmaDhruv2511** [comment]
I want to work on this issue can you please assign me?

**Comment by niladrix719** [comment]
@SharmaDhruv2511 go ahead

**Comment by ani1609** [comment]
@SharmaDhruv2511 yeah sure

**Comment by SharmaDhruv2511** [comment]
Hi just a quick update, I have resolve the issue.  I use the useEffect library to delay the loading seconds of google button.  

https://github.com/ani1609/Spendwise/assets/102755411/b4f999c4-8c9b-44d3-b923-76143c1bb669

if it looks good i am ready to raise a PR

**Comment by ani1609** [comment]
@SharmaDhruv2511 you can simply use css property to delay the animation, this will keep the code light weighted.

**Comment by SharmaDhruv2511** [comment]
done with the change. Can i raise the PR?

**Comment by niladrix719** [comment]
@SharmaDhruv2511 sure

**Comment by SharmaDhruv2511** [comment]
Done  with the small change. please review it
