### ISSUE TITLE
FEATURE REQUEST: Develop the functionality of 'Continue with google' using firebase authentication

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#190]
**Is your feature request related to a problem? Please describe.**
Every time the users have to create an account on our website, they need to enter all their details manually which is quite time taking.

**Describe the solution you'd like**
Instead of manually entering the credentials, the users should have an option to signup with their google account. Implement the use of Firebase Authentication to develop a signup with google feature for the users making it less time taking and convenient for the users.

File directory- client/src/components/Signup.js

<img width="427" alt="Screenshot 2023-12-12 at 5 00 59 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/89608c8a-383f-4068-bc42-2ebed8d39b57">

**Comment by Tanya1910** [comment]
please assign me this issue, I would like to work on it.

**Comment by ani1609** [comment]
@Tanya1910 go ahead please and ping us if you ever face any problem while solving the issue

**Comment by ani1609** [comment]
@Tanya1910 any update?

**Comment by GautamRaj-12** [comment]
Could you assign me please?
