### ISSUE TITLE
FEATURE REQUEST: Develop a react component named as MyProfile.js

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#193]
Make a new react component named as PredefinedTransactions.js in client/src/component folder with the below designs and elements.

<img width="420" alt="Screenshot 2023-12-12 at 7 47 15 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/0d759006-bfea-4b42-9dfd-2ed601b155e0">

Figma link for further references https://www.figma.com/file/LRX1qh4axVMFBn9qVbpSEK/Expense-Tracker?type=design&node-id=0-1&mode=design&t=rPSBKPhr4weB7Qjw-0 screen 4

Note- Please keep in mind that this a subcomponent so develop it in such a way that it can be integrated in a parent component.

**Comment by GautamRaj-12** [comment]
I can build it if assigned.

**Comment by ani1609** [comment]
@GautamRaj-12 sure
