### ISSUE TITLE
Non aligned transaction-form: The transactions form does not seem to be perfectly aligned and uniform

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#208]
<img width="448" alt="Screenshot 2023-12-13 at 9 10 26 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/68a1c136-d5b4-4270-95a9-9436d489d116">

Go to client/src/components/ExpenseTracker.js and change the complete ui of the transactions form according to the above mentioned Ui. Only keep the colour as like before.

**Comment by SHIVAA17** [comment]
Mentor ,May  I work on this issue.

**Comment by niladrix719** [comment]
@SHIVAA17 yes
