### ISSUE TITLE
Navbar Ui change

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#214]
Currently the right hand side of the navabr contains the below elements-

<img width="195" alt="Screenshot 2023-12-14 at 7 19 32 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/63617c71-4647-4927-9a2e-422d6ea7e672">

Change it to- 
<img width="116" alt="Screenshot 2023-12-14 at 7 17 14 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/9c8260c0-d816-4693-b109-5c1f590b1620">

Ignore the background

File location- client/src/components/Navbar.js

**Comment by Jaimin25** [comment]
want to work on this, please assign

**Comment by ani1609** [comment]
@Jaimin25 okay
