### ISSUE TITLE
Sending unwanted request to the server for login

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#216]
**Describe the bug**
After the user clicks on the login button will the required credentials, the login button is still clickable which is causing it to send unwanted requests to the server

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Logout of your accounts (if logged in)
3. Click on login button
4. Fill the form
5. Click on submit 'Login'

**Expected behavior**
The button should be disabled and the cursor should be pointing as not allowed till the current sent request is responded by the server.

**Screenshots**
<img width="334" alt="Screenshot 2023-12-14 at 7 53 16 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/480edeec-2bc1-4672-a5bc-981d79972448">

**Comment by C0DE-SLAYER** [comment]
i can work on this issue under KWOC23. assign it thanks
