### ISSUE TITLE
Sending unwanted request to the server for signup

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#217]
**Describe the bug**
After the user clicks on the signup button will the required credentials, the signup button is still clickable which is causing it to send unwanted requests to the server

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Logout of your accounts (if logged in)
3. Click on signup button
4. Fill the form
5. Click on submit 'Signup'

**Expected behavior**
The button should be disabled and the cursor should be pointing as not allowed till the current sent request is responded by the server.

**Screenshots**
<img width="342" alt="Screenshot 2023-12-14 at 8 02 41 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/30e979ca-bf22-4f5f-9bc9-dd2652a64e91">

**Comment by C0DE-SLAYER** [comment]
can you assign me this issue for KWOC23

**Comment by ani1609** [comment]
@C0DE-SLAYER yeah sure

**Comment by m-ahsan1** [comment]
Hey! fixed the issue. Please check.

**Comment by ani1609** [comment]
@C0DE-SLAYER are you working on this issue?

**Comment by C0DE-SLAYER** [comment]
> @C0DE-SLAYER are you working on this issue?

I was willing to work but as you you PR was open so I thought to skip it but seeing I will work on it and open a PR as soon as possible
