### ISSUE TITLE
Develop a new form inside PredefinedTransactions.js

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#228]
<img width="227" alt="Screenshot 2023-12-15 at 8 00 03 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/e1492da6-72af-47ae-a3b7-698c76cb01ad">

Develop a form in PredefinedTransactions.js inside client/src/components/profile folder with the above mentioned UI.

The form should pop up when the user clicks on the 'Add New Transaction' tab present inside PredefinedTransactions.js. It should look like this when clicked on the 'Add New Transaction'

<img width="481" alt="Screenshot 2023-12-15 at 7 55 29 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/9217f56f-1b3c-4ea9-b2ca-3f198b1291b7">

**Comment by ZSThai** [comment]
Can I try to solve this issue?

**Comment by ani1609** [comment]
@ZSThai sure

**Comment by yashitz07** [comment]
I would like to work on it

**Comment by ani1609** [comment]
@ZSThai are you working on this issue?

**Comment by ani1609** [comment]
@ZSThai any update?

**Comment by ani1609** [comment]
@yashitz07 can you work on this issue?

**Comment by GautamRaj-12** [comment]
Assign me please..
