### ISSUE TITLE
Implementing Validation and Error Handling in Signup Form.

### ISSUE THREAD

**Issue by Ayusht777** [ani1609/Spendwise#229]
The password should be at least 8 characters long. Incorporate capital letters, small letters, numbers, and symbols for good measure. Additionally, the name avoids using symbols or numbers. That would help with correct data.

**Comment by ani1609** [comment]
@Ayusht777 would you like to work on the issue?

**Comment by Ayusht777** [comment]
yes

**Comment by ani1609** [comment]
@Ayusht777 go ahead please and feel free to raise more issues related to bugs or feature requests

**Comment by Ayusht777** [comment]
Hello, I've identified an issue on the signup page where my implemented CSS styles conflict with Tailwind classes. To resolve this, I'm contemplating removing the custom CSS from the signup page and substituting all tag styles with Tailwind classes. If you approve, I'll proceed with this adjustment.

**Comment by ani1609** [comment]
@Ayusht777 you can proceed

**Comment by Ayusht777** [comment]
okay

**Comment by ani1609** [comment]
@Ayusht777 any updates?

**Comment by ayann07** [comment]
I would like to work on this issue under KWOC 2023.

**Comment by ani1609** [comment]
@ayann07 yeah sure
