### ISSUE TITLE
Feature Request: A Customised Scroll bar for Spendwise

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#230]
![Screenshot 2023-12-16 at 2 49 54 PM](https://github.com/ani1609/Spendwise/assets/91966855/f48ba735-43a1-4b92-b266-dfbbe87b7a50)

Make a Customised Scroll bar for Spendwise

**Comment by SHIVAA17** [comment]
@niladrix719  May I work on this Issue

**Comment by niladrix719** [comment]
yes go ahead @SHIVAA17
