### ISSUE TITLE
BUG: Form is closing when clicking outside of the form.

### ISSUE THREAD

**Issue by chandiran-v** [ani1609/Spendwise#231]
**Describe the bug**
The form to sign up/login is closed when we click on the screen except the form.

**To Reproduce**
1. Go to [Spendwise](https://spendwise-seven.vercel.app/)
2. Click on Login/Signup button
3. Click outside of the form
4. See the behavior

**Expected behavior**
The form should not be closed when we click outside of the form. By placing cross icon at the top right corner and adding function to close to the icon should solve the issue.

**Screenshots**

Uploading Bug.mp4…

**Comment by C0DE-SLAYER** [comment]
can you assign me this issue i would like to work on it

**Comment by ani1609** [comment]
@C0DE-SLAYER sure

**Comment by ani1609** [comment]
@chandiran-v actually i have developed the form in such way that clicking outside of it will close the form because the form has no dedicated closing button. Do let me know if you have any better option (like integrating a new cross button fro closing the form)

**Comment by ani1609** [comment]
@C0DE-SLAYER before working on the issue, please share the alternative you have thought about. We simply cannot restrict the user from closing the form.

**Comment by chandiran-v** [comment]
> @chandiran-v actually i have developed the form in such way that clicking outside of it will close the form because the form has no dedicated closing button. Do let me know if you have any better option (like integrating a new cross button fro closing the form)

Yes, integrating cross button will be more user friendly. Also I haven't seen any such design to close automatically when we click outside of the form. If I entering my credentials and in half way, accidentally pressed outside of the form, the form closes automatically without any warning/indication and also I have to redo the same process. If we give users a close button, it is much more convenient to use since the background also blurred. 
Also it is mandatory to signup/login, so as a user I must login/signup to use the app. Abruptly closing the form when clicking outside makes no sense in my opinion. What is your view @ani1609? Close the issue if I am wrong.

**Comment by ani1609** [comment]
@chandiran-v okay, lets add a cross button. Do you wanna work on this issue?

**Comment by chandiran-v** [comment]
Yes. I am interested.

**Comment by ani1609** [comment]
@chandiran-v okay
