### ISSUE TITLE
BUG REPORT: The transaction utility is getting hidden when the filter criteria does not matches any transaction

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#233]
**Describe the bug**
The transaction utility is getting hidden when the filter criteria does not matches any transaction

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Login to your account (or create new if not already)
3. Add some transactions (if not already)
4. Apply for a filter which has no matching transaction
5. See the error

**Expected behaviour**
The filter functionality should still be available so that the filter criteria could be changed because the user already has transactions

**Screenshots**

https://github.com/ani1609/Spendwise/assets/89239354/078c1df9-c8b2-4b0f-bcb1-9b786300ac84

**Comment by mendacium-a11y** [comment]
can i work on this @ani1609

**Comment by ani1609** [comment]
@mendacium-a11y sure

**Comment by mendacium-a11y** [comment]
seems like this issue has been fixed, i am unable to reproduce it

**Comment by ani1609** [comment]
@mendacium-a11y yeah. please look or wait other issues
