### ISSUE TITLE
Transition to Firebase Authentication and Removal of MongoDB for Login-Signup System

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#235]
Background:
Our current project utilizes MongoDB for the login-signup system. However, we have identified the need to migrate to Firebase Authentication, providing a more seamless and scalable solution for user management. This transition aims to enhance security, simplify authentication processes, and leverage the benefits offered by Firebase.

Objectives:
1. Migration to Firebase Authentication: Implement Firebase Authentication to replace the existing MongoDB-based login-signup system.
2. Removal of MongoDB Dependencies: Eliminate MongoDB-related code, configurations, and dependencies associated with user authentication.

Connect to mentors over slack channel for any doubts and help regarding the issue.

**Comment by Nupoor10** [comment]
Hello, can I take this up?

**Comment by ani1609** [comment]
@Nupoor10 sure.

Make a new collection in the firebase database named as 'users' which will contain all the users. And if you can, please implement the email verification process with firebase authentication. 

Please reach out to us on slack if you ned the access to the firebase database.

**Comment by ani1609** [comment]
@Nupoor10 you need to use this one cause this one comes with an  inbuilt email verification feature which we will be using.

**Comment by ani1609** [comment]
@Nupoor10 any update?

**Comment by Nupoor10** [comment]
Hello, apologies for the delay, my exams are going on. I will give an update on this issue tomorrow if that is okay.

**Comment by ani1609** [comment]
@Nupoor10 okay

**Comment by Nupoor10** [comment]
Hello, I won't be able to complete this issue in time due to my exams so I am unassigning myself
