### ISSUE TITLE
Feature Request - Implement Theme Switching Using React Context

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#236]
**Background:**
Our project aims to provide an enhanced user experience, and one way to achieve this is by allowing users to switch between different themes dynamically. We currently lack a robust theme management system, and we believe implementing a global theme context using React Context would greatly enhance our project.

**Feature Request:**
We are requesting the development of a React Context-based global variable to manage the theme state across our React application. This will allow users to switch between light and dark themes effortlessly, with the UI dynamically responding to their preferences.

**Comment by Sumandalai** [comment]
I want to contribute to this issue. Could you please assign it to me?

**Comment by ani1609** [comment]
@Sumandalai sure

**Comment by ani1609** [comment]
@Sumandalai any update?

**Comment by Sumandalai** [comment]
Hi @ani1609  , the work on adding dark mode is almost done. Probably, I'll complete it by tomorrow.

**Comment by ani1609** [comment]
@Sumandalai are you working on the Ui part too? If yes, please refer to the Figma file here (Screen- Desktop 5)
https://www.figma.com/file/LRX1qh4axVMFBn9qVbpSEK/Expense-Tracker?type=design&node-id=0-1&mode=design&t=RwJTaItYxbsjqqYn-0

and please store the primary dark colour, secondary dark colour, dark border colour in css global variables.

**Comment by Sumandalai** [comment]
![Screenshot (137)](https://github.com/ani1609/Spendwise/assets/123189815/9ecb4c49-c91b-49fd-8caa-302906a74971)
@ani1609 There are so many conflicts, but after pulling, I am not able to log in. Please help so that I can resolve the merge conflicts

**Comment by ani1609** [comment]
@ani1609 please ping me up on our slack channel

**Comment by ani1609** [comment]
@Sumandalai done
