### ISSUE TITLE
Feature Request - Implement Full Website Colour Palette Customisation

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#238]
**Background:**
In order to provide users with a more customisable and visually appealing experience, we are seeking to implement global CSS variables for colour customisation throughout our website. This feature will allow us to easily manage and update key color codes, such as the primary color and border colors, ensuring a consistent and harmonious visual identity.

**Feature Request:**
We are requesting the introduction of global CSS variables to manage key colour properties, specifically changing the primary colour to #B6CEFC, setting border colours to #6E9DF7. and icons colour to  6E9DF7

**Objectives:**
Global CSS Variables:
Implement CSS variables to store and manage key color codes globally.
Primary Color Customisation:
Set up a global CSS variable for the primary color and update the website to use #B6CEFC as the primary color.
Border Color Customization:
Set up a global CSS variable for border colours and update border styles across the website to use #6E9DF7.

Figma link- https://www.figma.com/file/LRX1qh4axVMFBn9qVbpSEK/Expense-Tracker?type=design&node-id=0-1&mode=design&t=ZtnsJ0W1PKcpCS7j-0 (Screen- Desktop 1)

**Comment by anuragsingh132200** [comment]
can i do this

**Comment by ani1609** [comment]
@anuragsingh132200 sure

**Comment by ani1609** [comment]
@anuragsingh132200 any update?

**Comment by elefrodi** [comment]
hi, i see this issue is still open, can i work on it?

**Comment by ani1609** [comment]
@elefrodi yeah sure
