### ISSUE TITLE
Validation for email field in Signup form

### ISSUE THREAD

**Issue by Anuj-Gill** [ani1609/Spendwise#239]
**Bug**
During signup, entering only "mail@a" as the email address is incorrectly accepted. This email lacks the expected format with a domain name and top-level domain, making it invalid.

**Solution**
This can be fixed with ZOD validation library.

**Screenshots**
![image](https://github.com/ani1609/Spendwise/assets/130141645/40feaae6-34f5-4aa2-b73d-67f0320cfae3)
This get's accepted and I got signedup!

**Comment by Anuj-Gill** [comment]
@ani1609 @niladrix719 Please assign this issue to me. I am learning express and learned about ZOD validation library, so I think I can fix this bug.

**Comment by ani1609** [comment]
@Anuj-Gill we have decided to shift the authentication process to firebase authentication where the users will be sent a verification link over email. Will your idea be helpful in that scenario?

**Comment by Anuj-Gill** [comment]
@ani1609 I believe yes, because we can use ZOD to pre-validate the email address format before sending it to Firebase for verification. This can improve server efficiency by catching obvious errors beforehand.

**Comment by niladrix719** [comment]
@Anuj-Gill sure go ahead

**Comment by ani1609** [comment]
@Anuj-Gill any update?

**Comment by Anuj-Gill** [comment]
@ani1609 I have created a PR. Please have a look.

**Comment by ani1609** [comment]
@Anuj-Gill done
