### ISSUE TITLE
Add ESLint for better code readability and uphelding set coding rules

### ISSUE THREAD

**Issue by mendacium-a11y** [ani1609/Spendwise#244]
**Is your feature request related to a problem? Please describe.**
The current project lacks consistent formatting standards or code formatters and linters, leading to potential readability issues and difficulties in maintaining the codebase.

**Describe the solution you'd like**
Implement ESLint for the project to enforce consistent coding standards, identify potential errors, and maintain code quality across the codebase. ESLint will help ensure adherence to predefined coding conventions, enhancing code readability and reducing the likelihood of bugs or inconsistencies.

**Describe alternatives you've considered**
Prettier can be implemented which is just a code formatter, so it would only check discrepancies in code through pre-set rules.However, ESLint is widely adopted and provides robust customization options and extensibility, making it a versatile and popular choice for code analysis and enforcement.

**Comment by ani1609** [comment]
@mendacium-a11y are you interested in working on the above issue?

**Comment by mendacium-a11y** [comment]
yes

**Comment by ani1609** [comment]
@mendacium-a11y assigning you the issue, go ahead please
