### ISSUE TITLE
Add Password Visibility Toggle Feature

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#246]
**Objective:**
Implement a password visibility toggle feature in the user authentication form to allow users to easily view and hide their entered password.

**Details:**
The current user authentication form includes a password input field for users to enter their passwords securely. However, there is no option for users to view their entered password. This feature is commonly seen in modern authentication forms for user convenience.

**Proposed Solution:**

Add an eye icon next to the password input field.
Allow users to toggle between password visibility and hidden state by clicking the eye icon.
Ensure the toggle functionality does not compromise security.

**Comment by duongruong** [comment]
Can I do it?

**Comment by ani1609** [comment]
@duongruong sure

**Comment by Balaji-Avk** [comment]
can i work on it?

**Comment by ayann07** [comment]
can I work for this under KWOC.

**Comment by mendacium-a11y** [comment]
hey, i have actually fixed this already, almost ready to push a pull request, if it isn't a problem @ani1609 @ayann07 ?

**Comment by ani1609** [comment]
@mendacium-a11y please make the Ui like this 
<img width="357" alt="Screenshot 2023-12-23 at 2 09 38 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/73197e1f-3021-4646-a3b1-5eeb356d514d">
(refer to the eye icon only)

**Comment by mendacium-a11y** [comment]
just for the icon or for the placement as well

**Comment by mendacium-a11y** [comment]
https://github.com/ani1609/Spendwise/assets/110321699/56204cb4-58c7-41b2-ba95-50ee6cf41b05

here's how it's looking now

**Comment by ani1609** [comment]
@mendacium-a11y good, please make the icon a little bit smaller and create a PR

**Comment by mendacium-a11y** [comment]
on it

**Comment by mendacium-a11y** [comment]
hey, @ani1609 , could you take a look at the pr whenver possible

**Comment by mendacium-a11y** [comment]
@ani1609 i have created another pr, i was having some trouble with my last branch, so couldn't commit to the same pr, you can have a look now, the animation also works like it should

**Comment by ani1609** [comment]
@mendacium-a11y done
