### ISSUE TITLE
Dark mode is inactive

### ISSUE THREAD

**Issue by Souvik34** [ani1609/Spendwise#273]
**Describe the bug**
The dark mode is inactive on clicking
**To Reproduce**
1. Go to 'home'
2. Click on 'moon icon'
3. Scroll down to '...'

**Expected behavior**
When clicked on the moon button the webpage will turn dark
**Screenshots**
<img width="948" alt="image" src="https://github.com/ani1609/Spendwise/assets/98397984/dc8ae0f9-f6e7-44d1-bfce-61e12ee3f230">
![image](https://github.com/ani1609/Spendwise/assets/98397984/922ea9b1-49e4-4588-ba55-f0be117a6f00)

Both in light and in dark mode the theme of the website remains same.
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 11

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Vivo Y56 5G
 - OS: [e.g. iOS8.1] Funtouch
 - Browser [e.g. stock browser, safari] chrome

**Additional context**

**Comment by Souvik34** [comment]
If you assign me the issue, then I shall merge the PR

**Comment by ani1609** [comment]
@Souvik34 the mentioned feature has been implemented by a contributor recently. Please look for some other issue to work on.
