### ISSUE TITLE
Colour coordination tweak for dark theme

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#275]
<img width="439" alt="Screenshot 2023-12-28 at 2 14 21 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/48759fa1-e0ad-49fb-8dfc-c435d39f0407">

Change the icon colours to 'rgba(19,43,57,1)' and the icon background-colour to '#335467' for dark theme.

**Comment by mshokoya** [comment]
assign to me pls

**Comment by ani1609** [comment]
@mshokoya done
