### ISSUE TITLE
Colour coordination for dark theme.

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#276]
<img width="439" alt="Screenshot 2023-12-28 at 2 14 21 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/ce34fd0d-3d56-427d-ae49-7941449ea776">

Change the border colour to '#B6CEFC80' when in dark theme

**Comment by mshokoya** [comment]
assign to me pls

**Comment by ani1609** [comment]
@mshokoya done
