### ISSUE TITLE
Colour coordination tweaks

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#277]
<img width="435" alt="Screenshot 2023-12-28 at 2 41 01 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/3af65ac3-8acd-4287-a9b5-2afd6f735c50">

Change the border colour to '#B6CEFC80' when in dark theme

**Comment by mshokoya** [comment]
assign to me pls

**Comment by ani1609** [comment]
@mshokoya done
