### ISSUE TITLE
Color coordination tweaks

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#278]
<img width="447" alt="Screenshot 2023-12-28 at 2 45 22 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/0a94d9ad-8246-4aa3-923a-454a9358b69e">

Change the colour of the hr tag to '#B6CEFC80' when in dark theme

**Comment by mshokoya** [comment]
assign to me pls

**Comment by ani1609** [comment]
@mshokoya completed
