### ISSUE TITLE
Chart labels not visible in dark mode

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#279]
**Describe the bug**

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Log in to your account (or create one if not already)
3. Add some expense transactions (if not already)
4. Switch to dark mode (if currently in light mode)
5. See error

**Expected behaviour**
The labels should be visible

**Screenshots**
<img width="615" alt="Screenshot 2023-12-28 at 2 46 07 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/c8224fca-70c8-4357-9fdd-93af43586553">

Chnage the colour of the labels to '#B6CEFC80' when in dark mode

**Comment by C0DE-SLAYER** [comment]
Assign me this issue for KWOC23
