### ISSUE TITLE
Change border-colour

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#280]
<img width="615" alt="Screenshot 2023-12-28 at 2 46 07 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/bae16c7d-7354-49bf-a46e-c852068fb1bf">

Change the colour of the border of the pie chart sections to '#B6CEFC80' when in dark mode.

**Comment by C0DE-SLAYER** [comment]
Can you assign me this issue for KWOC23

**Comment by ani1609** [comment]
@C0DE-SLAYER sure
