### ISSUE TITLE
Change scroll-bar colour

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#281]
<img width="21" alt="Screenshot 2023-12-28 at 2 54 42 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/58615690-8bb8-4f8f-b186-74ae5b0de346">

Change the colour of the scrollbar thumb to 'rgba(19,43,57,1)' and the colour of the track-pad to '#959595' when in dark mode.

**Comment by mshokoya** [comment]
assign to me pls

**Comment by ani1609** [comment]
@mshokoya sure
