### ISSUE TITLE
Change transaction form input border colours

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#294]
<img width="480" alt="Screenshot 2023-12-29 at 2 17 03 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/35d55a87-8699-47f2-898a-cb96db26d12e">

Change the border colours of 'Amount'. 'Category', 'Description', and 'Date' forms to '#B6CEFC80' when in dark mode

**Comment by ShahnawazHussain28** [comment]
Please assign this issue to me. Let me fix this really quick

**Comment by ani1609** [comment]
@ShahnawazHussain28 sure

**Comment by ShahnawazHussain28** [comment]
It is resolved. Please merge the PR #306

**Comment by ani1609** [comment]
@ShahnawazHussain28 you have removed some of the css properties in you latest commit where you tried to resolve the merge conflicts

Current production views are- 
<img width="1440" alt="Screenshot 2023-12-30 at 1 01 46 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/8adea2c7-4827-47a8-a9ca-e1fb2f8d751f">
<img width="1440" alt="Screenshot 2023-12-30 at 1 01 55 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/0598fa93-cb1e-43b1-8171-3df2ab59d0b0">


But the preview of your PR looks like-
<img width="1440" alt="Screenshot 2023-12-30 at 1 01 02 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/ec1c8c1d-e263-44f2-ac29-b65a1b6217c7">
<img width="1440" alt="Screenshot 2023-12-30 at 1 01 12 AM" src="https://github.com/ani1609/Spendwise/assets/89239354/50216124-22d4-4769-9c7d-fcd33ea483c9">


Try to commit your changes after taking a pull from the main branch

**Comment by ani1609** [comment]
@ShahnawazHussain28 one more thing, !important property is used for setting border colours in. plain ExpenseTracker.css file, please remove them and use only tailwind css

**Comment by ShahnawazHussain28** [comment]
Thank you for the providing the comparative analysis. But we are using tailwind dark mode config. If a property is marked as important in the css file. Tailwind cannot override it using the dark: prefix. Have to modify the css file either way.

**Comment by ani1609** [comment]
@ShahnawazHussain28 i too realised that and that is why i asked you to delete those plain css properties

**Comment by ShahnawazHussain28** [comment]
It is using same css properties at many places. Almost all element contain the same border color style. It should not be set through tailwind because if you want to change a color you have to do it everywhere. That's why I've created a css variable for the dark mode border color and assigned them through css. Now you just have to change the variable value if you want and boom, everything will update.
