### ISSUE TITLE
Change border colours of the transactions

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#295]
<img width="453" alt="Screenshot 2023-12-29 at 2 17 12 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/91814a39-eeda-4035-8f5a-d8a5ecc3e5e5">

Change the border of income and expense transactions to '#B6CEFC80' when in dark mode.

**Comment by Sabbirfeni** [comment]
Hey Ankit Chowdhury,

Hope you are doing well. I have check the issue and interested on fix it. Please assign the issue to me.

Thanks,
Shabbir

**Comment by ani1609** [comment]
@Sabbirfeni sure

**Comment by Sabbirfeni** [comment]
Thanks, I am working on it.
