### ISSUE TITLE
Change the background colour of transactions

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#296]
<img width="453" alt="Screenshot 2023-12-29 at 2 17 12 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/d9cad77b-1044-4c6a-a7d4-fe63d55d91c6">

Change the background colour of the transactions to '#011019' when in dark theme.

**Comment by NJacksonDev** [comment]
Can you assign this to me?

**Comment by ani1609** [comment]
@NJacksonDev sure
