### ISSUE TITLE
Change the background colour of the transactions filters

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#297]
<img width="443" alt="Screenshot 2023-12-29 at 2 26 20 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/dd026328-fab9-41bd-bb29-d9b071a98f4f">

Change the background of the transactions filters (type, category and date) to '#011019' when in dark theme.

**Comment by A-4-Atom** [comment]
Hi, I'd like to fix it , can you assign it to me?

**Comment by ani1609** [comment]
@A-4-Atom yes please!

**Comment by A-4-Atom** [comment]
@ani1609 I've changed the background colors as requested, however I also noticed that the color of dropdown menu does not look good on dark theme (see image below) plus it's hard to see the text. If you want i can fix that.

![image](https://github.com/ani1609/Spendwise/assets/61468834/84de2ec6-f14e-4a49-9a85-62973224b422)

**Comment by ani1609** [comment]
@A-4-Atom please raise a new issue for this and leave a comment on the issue. i'll assign you the issue
