### ISSUE TITLE
Factorise the ExpenseTracker.css file

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#299]
Make a new css file in client/src/styles folder named as 'TransactionForm.css' and move all the css properties related to TransactionForm.js component (present in client/src/components folder) from 'ExpenseTracker.css' to the newly created file.

**Comment by ayann07** [comment]
I would like to work on this under KWOC 2023.

**Comment by ani1609** [comment]
@ayann07 sure

**Comment by ani1609** [comment]
@ani1609 are you working on this issue?

**Comment by SharmaDhruv2511** [comment]
I want to work on this task. Can you please assign it to me @ani1609

**Comment by ani1609** [comment]
@ani1609 sure

**Comment by ani1609** [comment]
@SharmaDhruv2511 sure

**Comment by SharmaDhruv2511** [comment]
Hi @ani1609 . I have one doubt. After creating the file do i have to copy the code of ExpenseTracker.css to Transactionform.css without changing any code right?

**Comment by SharmaDhruv2511** [comment]
@ani1609  I have successfully created a PR to the issue. I have review all the changes and are good from my side. Kindly review it and merge it and if there is any change please tell me.

**Comment by SharmaDhruv2511** [comment]
@ani1609 ???

**Comment by ani1609** [comment]
@SharmaDhruv2511 please wait, we will look into your PR when even possible

**Comment by SharmaDhruv2511** [comment]
Due to the end evaluation of Kwoc 2023 J am asking to review it. @ani1609
