### ISSUE TITLE
Set the Transaction input forms to transparent

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#301]
<img width="480" alt="Screenshot 2023-12-29 at 2 17 03 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/6579e47e-10be-499b-a880-28764d4d1c92">

Change the background of 'Amount'. 'Category', 'Description', and 'Date' forms to transparent.

**Comment by Not-Sahil-Raja** [comment]
Can you assign this  ?

**Comment by ani1609** [comment]
@Not-Sahil-Raja sure
