### ISSUE TITLE
Arrow and calendar icons in transactions filter are not visible in dark mode

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#313]
**Describe the bug**
Arrow and calendar icons in transactions filters (type, category and date) are not visible in dark mode

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app/
2. Login to your account (or create one)
3. Add transaction(s)
4. Switch to dark mode (if not already)
5. See the error

**Expected behaviour**
The arrow and calendar icons should change to a different colour when in dark mode so that they can be visible in dark mode. Change the icons colour to '#B6CEFC80' when in dark mode.

**Screenshots**
<img width="437" alt="Screenshot 2023-12-31 at 2 55 57 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/afef89a2-d703-43ab-ae57-ba7960355974">

**Comment by ghubrakesh** [comment]
Hey @ani1609, I would like to work on this issue. Can you please assign it to me?

**Comment by ani1609** [comment]
@ghubrakesh sure

**Comment by Jaimin25** [comment]
can work on this please assign to me

**Comment by Bikram-ghuku** [comment]
Can I work on this issue??
Please assign me this

**Comment by ani1609** [comment]
@Bikram-ghuku sure
