### ISSUE TITLE
Weird behaviour of colour shifts in transaction form

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#317]
**Describe the bug**
The placeholders of category and date form are having a weird behaviour in the colour shifts while switching between themes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://spendwise-seven.vercel.app/
2. Click on login (or create account if not already)
3. Switch between light and dark themes by clicking on the theme icon in the navbar.

**Expected behaviour**
The colour shifts should be natural as like that of amount and description form.

**Screenshots**

https://github.com/ani1609/Spendwise/assets/89239354/c9832bab-dbd7-4576-a70c-aababbe585d8

**Comment by Jaimin25** [comment]
Want to work on this, please assign it to me

**Comment by Jaimin25** [comment]
@ani1609

**Comment by ani1609** [comment]
@Jaimin25 ok
