### ISSUE TITLE
Transaction Form allows future dates to be entered

### ISSUE THREAD

**Issue by Anuj-Gill** [ani1609/Spendwise#323]
**Describe the bug**
Transaction Form allows future dates to be entered, even though only past or present dates should be accepted.

**Expected behavior**
The form should prevent the submission and display an error message if a future date is selected.

**Comment by Anuj-Gill** [comment]
Hello @ani1609 , I have already solved this problem. If possible, please assign this issue so that I can create a PR.

**Comment by ani1609** [comment]
@Anuj-Gill okay
