### ISSUE TITLE
Add: Error Page

### ISSUE THREAD

**Issue by AaadityaG** [ani1609/Spendwise#335]
**Describe the bug**
There is no error page (404)

**To Reproduce**
https://spendwise-seven.vercel.app/profil (speling mistake)

**Expected behavior**
Ther must be a error page and button to go back

**Screenshots**
![Capture](https://github.com/ani1609/Spendwise/assets/114663382/e57a1fc6-d72c-4dfc-bfb2-130bc4c0ad6a)

**Additional context**
Participating in KWOC

**Comment by AaadityaG** [comment]
Please allow me to work on it!

**Comment by ani1609** [comment]
@AaadityaG sure
