### ISSUE TITLE
Feature Request: Enhanced UI For Transactions Form

### ISSUE THREAD

**Issue by niladrix719** [ani1609/Spendwise#85]
**Describe the solution you'd like**

Requesting an improved UI for the transactions form to enhance user experience and streamline data input.

![Screenshot 2023-12-04 at 9 09 51 PM](https://github.com/ani1609/Spendwise/assets/91966855/ddc82b00-a6ca-4daa-ab11-cdfb5eaf07f8)

Make sure you join our slack channel for further discussions and announcements.

**Comment by niladrix719** [comment]
Yes this issue is under KWoC, You can make a PR for it

**Comment by niladrix719** [comment]
@JAYBORICHA07 any updates?

**Comment by niladrix719** [comment]
This issue is open to work on

**Comment by harshikagoyal14** [comment]
@niladrix719  I can work on this issue, Can you please assign it to me?

**Comment by ani1609** [comment]
@harshikagoyal14 yes sure

**Comment by ani1609** [comment]
@harshikagoyal14 match the form ui according to the screem 'Desktop 2' on https://www.figma.com/file/LRX1qh4axVMFBn9qVbpSEK/Expense-Tracker?type=design&node-id=0-1&mode=design&t=7UOKsCKZCfLZ9Gtz-0

**Comment by harshikagoyal14** [comment]
@ani1609 Ok

**Comment by ani1609** [comment]
@harshikagoyal14 you haven't started working on this issue till now right?

**Comment by harshikagoyal14** [comment]
@ani1609 I had already started.

**Comment by ani1609** [comment]
@harshikagoyal14 ok then please do continue. @JAYBORICHA07 your issue was assigned to you for four days and after getting not response, we had to unsaying you. please look for some other issue to work on

**Comment by harshikagoyal14** [comment]
![Image 13-12-23 at 7 34 PM](https://github.com/ani1609/Spendwise/assets/109340203/d3a843c5-a346-4b4b-ab9c-d5f8a7fb426f)
Is this Ok?

**Comment by harshikagoyal14** [comment]
@ani1609 can I make PR?

**Comment by ani1609** [comment]
@harshikagoyal14 please design the category and date input forms like this

<img width="526" alt="Screenshot 2023-12-14 at 2 30 23 PM" src="https://github.com/ani1609/Spendwise/assets/89239354/dc690c6d-34c4-4cc6-b343-4b3b683a5677">

**Comment by harshikagoyal14** [comment]
![Image 14-12-23 at 8 44 PM](https://github.com/ani1609/Spendwise/assets/109340203/b04b64b1-b366-4afa-bb35-005ec4c09693)
is this ok?

**Comment by ani1609** [comment]
@harshikagoyal14 make all the input boxes same in height and width

**Comment by harshikagoyal14** [comment]
![Image 14-12-23 at 10 01 PM](https://github.com/ani1609/Spendwise/assets/109340203/62824e87-d368-424f-bf4f-44de35808936)

**Comment by ani1609** [comment]
@harshikagoyal14 looks good, create a PR please

**Comment by harshikagoyal14** [comment]
I have made PR. Can you pls check
