### ISSUE TITLE
Bug: Lack of padding below the expense chart

### ISSUE THREAD

**Issue by ani1609** [ani1609/Spendwise#87]
**Describe the bug**
There needs to be some space between the chart and the bottom line of the screen (padding).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://spendwise-seven.vercel.app/
2. Log in (or create an account)
3. Add some expense transactions (if not previously added)
4. Scroll down to the bottom of the page
5. See error

**Expected behaviour**
There chart labels seems to be congested with the bottom line of the screen.

**Screenshots**
![WhatsApp Image 2023-12-04 at 21 45 18](https://github.com/ani1609/Spendwise/assets/89239354/b0e7c62e-a0db-45c5-a028-1cfadda72a8b)

**Comment by TamLeCNTT** [comment]
I want to work on this can you assign this to me?

**Comment by niladrix719** [comment]
@TamLeCNTT sure

**Comment by chandiran-v** [comment]
Hi, can i work on this issue? This needs to be fixed in mobile screen range also. #KWoC 
Please assign this to me.
![image](https://github.com/ani1609/Spendwise/assets/149917528/b869bf15-7727-4da6-93d2-26cd875bc0f6)

**Comment by niladrix719** [comment]
@chandiran-v sure go ahead
